config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get '/signup' => 'users#new'
  get '/users' => 'users#create'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  get '/auth/:provider' => 'omniauth#auth', as: :auth
  get '/auth/:provider/callback' => 'session#create'
  get '/auth/failure' => 'session#failure'

  root 'welcome#index'
  resources :categories
  resources :terms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :terms, through: :rosters
  has_many :rosters
end

app/models/roster.rb
class Roster < ApplicationRecord
  belongs_to :term
  belongs_to :category
end

app/models/term.rb
class Term < ApplicationRecord
  has_many :categories, through: :rosters
  has_many :rosters
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid']).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user=(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  #returns boolean if logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def authorize!
    redirect_to login_path unless logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :subject, term_ids: [])
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    # to be deleted for Oauth

    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def failure
    #show failure
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!
  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { render :show, status: :ok, location: @term }
      else
        format.html { render :edit }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url, notice: 'Term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_params
      params.require(:term).permit(:name, :definition, :author, :web_link, category_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to signup_path
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :subject
    = f.text_field :subject
  .field
    = f.label :terms
    = f.collection_check_boxes(:term_ids, Term.all, :id, :name)
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table.table.table-striped.table-hover
  %thead
    %tr
      %th Name
      %th Subject
      %th Terms
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.subject
        %td= category.terms.length
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Subject:
  = @category.subject
%p
  %b Terms:
  - @category.terms.each do |term|
    = term.name
= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TiyOauthGlossary
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => root_path}
            %img(src="logo-white.png" height="28px")
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              %a{:href => terms_path} Terms

            %li
              %a{:href => categories_path} Categories
          %form.navbar-form.navbar-left{:role => "search"}
            .form-group
              %input.form-control{:placeholder => "Search", :type => "text"}/
            %button.btn.btn-default{:type => "submit"} Submit
          %ul.nav.navbar-nav.navbar-right
            - if logged_in?
              %li
                =current_user.name
              %li
                = link_to "Log Out", logout_path
            -else
              %li
                =link_to "Login", login_path
              %li
                =link_to "Signup", signup_path
  .main-body
    = yield

app/views/session/new.html.haml
%h1 Login

= link_to 'Login with Github', auth_path(provider: 'github')

app/views/terms/_form.html.haml
= form_for @term do |f|
  - if @term.errors.any?
    #error_explanation
      %h2= "#{pluralize(@term.errors.count, "error")} prohibited this term from being saved:"
      %ul
        - @term.errors.full_messages.each do |msg|
          %li= msg
  %form.form-horizontal
    %fieldset
      .form-group
        .field
          = f.label :name
          = f.text_field :name
        .field
          = f.label :definition
          = f.text_area :definition
        .field
          = f.label :author
          = f.text_field :author
        .field
          = f.label :web_link
          = f.text_field :web_link
        .field
          = f.label :categories
          = f.collection_check_boxes(:category_ids, Category.all, :id, :name)
        .actions
          = f.submit 'Save'

app/views/terms/edit.html.haml
%h1 Editing term

= render 'form'

= link_to 'Show', @term
\|
= link_to 'Back', terms_path

app/views/terms/index.html.haml
%h1 Listing terms

%table.table.table-striped.table-hover
  %thead
    %tr
      %th Name
      %th Definition
      %th Author
      %th Web link
      %th Categories
      %th
      %th
      %th

  %tbody
    - @terms.each do |term|
      %tr
        %td= term.name
        %td= term.definition
        %td= term.author
        %td= term.web_link
        %td= term.categories.length
        %td= link_to 'Show', term
        %td= link_to 'Edit', edit_term_path(term)
        %td= link_to 'Destroy', term, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Term', new_term_path

app/views/terms/new.html.haml
%h1 New term

= render 'form'

= link_to 'Back', terms_path

app/views/terms/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @term.name
%p
  %b Definition:
  = @term.definition
%p
  %b Author:
  = @term.author
%p
  %b Web link:
  = @term.web_link
%p
  %b Categories:
  - @term.categories.each do |category|
    =category.name

= link_to 'Edit', edit_term_path(@term)
\|
= link_to 'Back', terms_path

app/views/users/new.html.haml
%h1 Sign-up


= form_for(@user) do |f|
  Name:
  = f.text_field :name
  Email:
  = f.text_field :email
  Password:
  = f.password_field :password
  Password Confirmation:
  = f.password_field :password_confirmation
  = f.submit "Submit"

app/views/welcome/index.html.haml
%h1 TIY
%p Welcome to TIY Online Glossary